Importing the necessary libraries

In [45]:
import pandas as pd

In [46]:
from pathlib import Path

Inspecting the Dataset Before Scaling

Before applying the scaling procedure, the structure and dimensions of the dataset are examined.

This allows us to confirm the number of observations and features and verify that the dataset contains numerical variables suitable for the scaling procedure.

The dataset contains 10,127 observations and 32 features.

In [47]:
path = Path("/content/encoded_data (2).csv")
df = pd.read_csv(path)
df.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,Marital_Status_Single,Marital_Status_Unknown,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_Less than $40K,Income_Category_Unknown,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,45,3,39,5,1,3,12691.0,777,11914.0,1.335,...,0,0,0,1,0,0,0,0,0,0
1,49,5,44,6,1,2,8256.0,864,7392.0,1.541,...,1,0,0,0,0,1,0,0,0,0
2,51,3,36,4,1,0,3418.0,0,3418.0,2.594,...,0,0,0,0,1,0,0,0,0,0
3,40,4,34,3,4,1,3313.0,2517,796.0,1.405,...,0,1,0,0,0,1,0,0,0,0
4,40,3,21,5,1,0,4716.0,0,4716.0,2.175,...,0,0,0,1,0,0,0,0,0,0

In [48]:
df.shape

(10127, 35)

In [49]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer_Age,10127.0,46.325960,8.016814,26.000000,41.000000,46.000000,52.000000,73.000000
Dependent_count,10127.0,2.346203,1.298908,0.000000,1.000000,2.000000,3.000000,5.000000
Months_on_book,10127.0,35.928409,7.986416,13.000000,31.000000,36.000000,40.000000,56.000000
Total_Relationship_Count,10127.0,3.812580,1.554408,1.000000,3.000000,4.000000,5.000000,6.000000
Months_Inactive_12_mon,10127.0,2.341167,1.010622,0.000000,2.000000,2.000000,3.000000,6.000000
Contacts_Count_12_mon,10127.0,2.455317,1.106225,0.000000,2.000000,2.000000,3.000000,6.000000
Credit_Limit,10127.0,8631.953698,9088.776650,1438.300000,2555.000000,4549.000000,11067.500000,34516.000000
Total_Revolving_Bal,10127.0,1162.814061,814.987335,0.000000,359.000000,1276.000000,1784.000000,2517.000000
Avg_Open_To_Buy,10127.0,7469.139637,9090.685324,3.000000,1324.500000,3474.000000,9859.000000,34516.000000
Total_Amt_Chng_Q4_Q1,10127.0,0.759941,0.219207,0.000000,0.631000,0.736000,0.859000,3.397000
Total_Trans_Amt,10127.0,4404.086304,3397.129254,510.000000,2155.500000,3899.000000,4741.000000,18484.000000
Total_Trans_Ct,10127.0,64.858695,23.472570,10.000000,45.000000,67.000000,81.000000,139.000000
Total_Ct_Chng_Q4_Q1,10127.0,0.712222,0.238086,0.000000,0.582000,0.702000,0.818000,3.714000
Avg_Utilization_Ratio,10127.0,0.274894,0.275691,0.000000,0.023000,0.176000,0.503000,0.999000
Avg_Transaction_Amount,10127.0,62.612717,26.404198,19.137931,47.514573,55.794872,65.476673,190.193182
Revolving_Balance_Ratio,10127.0,0.274892,0.275689,0.000000,0.022714,0.175650,0.502691,0.998768
Transaction_Activity_per_Relationship,10127.0,23.631660,22.075832,2.500000,11.000000,15.750000,25.666667,138.000000
Gender_M,10127.0,0.470919,0.499178,0.000000,0.000000,0.000000,1.000000,1.000000
Education_Level_Doctorate,10127.0,0.044534,0.206289,0.000000,0.000000,0.000000,0.000000,1.000000
Education_Level_Graduate,10127.0,0.308877,0.462053,0.000000,0.000000,0.000000,1.000000,1.000000
Education_Level_High School,10127.0,0.198776,0.399098,0.000000,0.000000,0.000000,0.000000,1.000000
Education_Level_Post-Graduate,10127.0,0.050953,0.219912,0.000000,0.000000,0.000000,0.000000,1.000000
Education_Level_Uneducated,10127.0,0.146835,0.353959,0.000000,0.000000,0.000000,0.000000,1.000000
Education_Level_Unknown,10127.0,0.149995,0.357084,0.000000,0.000000,0.000000,0.000000,1.000000
Marital_Status_Married,10127.0,0.462822,0.498641,0.000000,0.000000,0.000000,1.000000,1.000000
Marital_Status_Single,10127.0,0.389355,0.487628,0.000000,0.000000,0.000000,1.000000,1.000000
Marital_Status_Unknown,10127.0,0.073961,0.261720,0.000000,0.000000,0.000000,0.000000,1.000000
Income_Category_$40K - $60K,10127.0,0.176755,0.381480,0.000000,0.000000,0.000000,0.000000,1.000000
Income_Category_$60K - $80K,10127.0,0.138442,0.345380,0.000000,0.000000,0.000000,0.000000,1.000000
Income_Category_$80K - $120K,10127.0,0.151575,0.358626,0.000000,0.000000,0.000000,0.000000,1.000000
Income_Category_Less than $40K,10127.0,0.351634,0.477504,0.000000,0.000000,0.000000,1.000000,1.000000
Income_Category_Unknown,10127.0,0.109805,0.312663,0.000000,0.000000,0.000000,0.000000,1.000000
Card_Category_Gold,10127.0,0.011455,0.106416,0.000000,0.000000,0.000000,0.000000,1.000000
Card_Category_Platinum,10127.0,0.001975,0.044398,0.000000,0.000000,0.000000,0.000000,1.000000
Card_Category_Silver,10127.0,0.054804,0.227608,0.000000,0.000000,0.000000,0.000000,1.000000

Feature Scaling:

We’re going to use the StandardScaler because it uses standardization (with each feature centered around a mean of approximately 0 and scaled to a standard deviation of approximately 1) which is particularly appropriate when features have different units and magnitudes and when we want them to contribute on a comparable standardized scale. This is important because K-Means uses distances to form clusters and PCA is sensitive to the scale of the input variables. Without scaling, variables with larger numerical magnitudes, such as transaction amounts and credit limits, could dominate variables measured on smaller scales.

In [50]:
df.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,Marital_Status_Single,Marital_Status_Unknown,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_Less than $40K,Income_Category_Unknown,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,45,3,39,5,1,3,12691.0,777,11914.0,1.335,...,0,0,0,1,0,0,0,0,0,0
1,49,5,44,6,1,2,8256.0,864,7392.0,1.541,...,1,0,0,0,0,1,0,0,0,0
2,51,3,36,4,1,0,3418.0,0,3418.0,2.594,...,0,0,0,0,1,0,0,0,0,0
3,40,4,34,3,4,1,3313.0,2517,796.0,1.405,...,0,1,0,0,0,1,0,0,0,0
4,40,3,21,5,1,0,4716.0,0,4716.0,2.175,...,0,0,0,1,0,0,0,0,0,0

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df)

In [52]:
scaled_df = pd.DataFrame(
    X_scaled,
    columns=df.columns,
    index=df.index)

Confirming the scaled data.

In [53]:
scaled_df.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,...,Marital_Status_Single,Marital_Status_Unknown,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_Less than $40K,Income_Category_Unknown,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,-0.165406,0.503368,0.384621,0.763943,-1.327136,0.492404,0.446622,-0.473422,0.488971,2.623494,...,-0.798507,-0.282609,-0.463363,2.494645,-0.422675,-0.736437,-0.351212,-0.107644,-0.044484,-0.240794
1,0.333570,2.043199,1.010715,1.407306,-1.327136,-0.411616,-0.041367,-0.366667,-0.008486,3.563293,...,1.252337,-0.282609,-0.463363,-0.400859,-0.422675,1.357890,-0.351212,-0.107644,-0.044484,-0.240794
2,0.583058,0.503368,0.008965,0.120579,-1.327136,-2.219655,-0.573698,-1.426858,-0.445658,8.367214,...,-0.798507,-0.282609,-0.463363,-0.400859,2.365881,-0.736437,-0.351212,-0.107644,-0.044484,-0.240794
3,-0.789126,1.273283,-0.241473,-0.522785,1.641478,-1.315636,-0.585251,1.661686,-0.734100,2.942843,...,-0.798507,3.538459,-0.463363,-0.400859,-0.422675,1.357890,-0.351212,-0.107644,-0.044484,-0.240794
4,-0.789126,0.503368,-1.869317,0.763943,-1.327136,-2.219655,-0.430877,-1.426858,-0.302868,6.455682,...,-0.798507,-0.282609,-0.463363,2.494645,-0.422675,-0.736437,-0.351212,-0.107644,-0.044484,-0.240794

In [54]:
scaled_df.to_csv(
    "scaled_data_for_clustering.csv",
    index=False)